# Generated by Django 3.2.5 on 2021-07-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_framework_tracking', '0011_auto_20201117_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
            ],
            options={
                'verbose_name': 'API request log',
                'verbose_name_plural': 'API request logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest_framework_tracking.apirequestlog',),
        ),
    ]
