# Generated by Django 2.1.15 on 2020-02-13 21:22

import apps.user.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.base.UserManager()),
            ],
        ),
    ]
