# Generated by Django 2.1.7 on 2019-04-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190404_1708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmedia',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='user',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
