# Generated by Django 2.0.5 on 2018-08-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
