# Generated by Django 2.1.2 on 2018-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20181130_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
