# Generated by Django 3.2.5 on 2021-07-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(db_index=True, max_length=255)),
                ('args', models.TextField(blank=True)),
                ('kwargs', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('schedule', models.IntegerField(blank=True, db_index=True, null=True)),
                ('run_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('incomplete', 'Incomplete')], default='waiting', max_length=10)),
            ],
            options={
                'ordering': ('-completed_at', '-run_at'),
            },
        ),
    ]
