# Generated by Django 2.2.1 on 2020-11-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='waiting', max_length=10),
        ),
    ]
