# Generated by Django 3.0.7 on 2020-12-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20201130_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('incomplete', 'Incomplete')], default='waiting', max_length=10),
        ),
    ]
