# Generated by Django 3.0.5 on 2020-04-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='section',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
