# Generated by Django 3.0.5 on 2020-04-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Work'},
        ),
        migrations.AddField(
            model_name='page',
            name='sub_title',
            field=models.CharField(default='cool', max_length=255),
            preserve_default=False,
        ),
    ]
