# Generated by Django 3.0.5 on 2020-04-17 17:50

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200417_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='layout',
            field=models.CharField(choices=[('simple', 'Simple'), ('sectioned', 'Sectioned')], default='simple', max_length=30),
        ),
        migrations.AddField(
            model_name='page',
            name='sidebar',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
