# Generated by Django 3.0.5 on 2020-04-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='feature_images'),
        ),
    ]
