# Generated by Django 2.1 on 2018-08-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='handler',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
