# Generated by Django 2.1.7 on 2019-07-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='api_response_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='api_response_text',
            field=models.TextField(default=''),
        ),
    ]
